### ISSUE TITLE
xyo bridge

### ISSUE THREAD

**Issue by Rancid1616** [XYOracleNetwork/sdk-xyo-client-swift#1]
joshuanaylor@Joshuas-iMac ~ % npm i --save @xyo-network/sdk-xyo-client-js
yarn add @xyo-network/sdk-xyo-client-js
npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> keccak@3.0.2 install /Users/joshuanaylor/node_modules/keccak
> node-gyp-build || exit 0

npm WARN saveError ENOENT: no such file or directory, open '/Users/joshuanaylor/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/joshuanaylor/package.json'
npm WARN joshuanaylor No description
npm WARN joshuanaylor No repository field.
npm WARN joshuanaylor No README data
npm WARN joshuanaylor No license field.

+ @xyo-network/sdk-xyo-client-js@2.14.13
added 101 packages from 323 contributors and audited 101 packages in 26.23s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

joshuanaylor@Joshuas-iMac ~ % yarn add @xyo-network/sdk-xyo-client-js
zsh: command not found: yarn
joshuanaylor@Joshuas-iMac ~ % npm i --save @xyo-network/sdk-xyo-client-js
npm WARN saveError ENOENT: no such file or directory, open '/Users/joshuanaylor/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/joshuanaylor/package.json'
npm WARN joshuanaylor No description
npm WARN joshuanaylor No repository field.
npm WARN joshuanaylor No README data
npm WARN joshuanaylor No license field.

+ @xyo-network/sdk-xyo-client-js@2.14.13
updated 1 package and audited 183 packages in 10.624s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

joshuanaylor@Joshuas-iMac ~ % yarn add @xyo-network/sdk-xyo-client-js
zsh: command not found: yarn
joshuanaylor@Joshuas-iMac ~ % npm i --save @xyo-network/sdk-xyo-client-js
npm WARN saveError ENOENT: no such file or directory, open '/Users/joshuanaylor/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/joshuanaylor/package.json'
npm WARN joshuanaylor No description
npm WARN joshuanaylor No repository field.
npm WARN joshuanaylor No README data
npm WARN joshuanaylor No license field.

+ @xyo-network/sdk-xyo-client-js@2.14.13
updated 1 package and audited 183 packages in 4.262s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

joshuanaylor@Joshuas-iMac ~ % `npm fund`
zsh: permission denied: /Users/joshuanaylor
joshuanaylor@Joshuas-iMac ~ % yarn add @xyo-network/sdk-xyo-client-js
zsh: command not found: yarn
joshuanaylor@Joshuas-iMac ~ % if (process.env.NODE_ENV === 'production') {
    module.exports = require('./matic-web3.node.min.js')
} else {
    module.exports = require('./matic-web3.node.js')
}
zsh: == not found
zsh: number expected
joshuanaylor@Joshuas-iMac ~ % dependencies: [
.package(url: "https://github.com/XYOracleNetwork/sdk-xyo-client-swift.git", .upToNextMajor(from: "2.0.3")),
],
zsh: command not found: dependencies:
zsh: bad pattern: .package(url: https://github.com/XYOracleNetwork/sdk-xyo-client-swift.git, .upToNextMajor(from: 2.0.3)),
joshuanaylor@Joshuas-iMac ~ % let panel = XyoPanel(archive: 'test', apiDomain: "https://api.archivist.xyo.network", witnesses: [XyoSystemInfoWitness()])
zsh: parse error near `)'
joshuanaylor@Joshuas-iMac ~ % panel.report(nil, nil)
zsh: unknown file attribute: i
joshuanaylor@Joshuas-iMac ~ % >....                                             
    //maybe we can get the number from the address more easily
    static verifyAddress(msg, signature, address) {
        let valid = false;
        for (let i = 0; i < 4; i++) {
            try {
                const publicKey = this.ecContext.recoverPubKey(toUint8Array(msg), toUint8Array(signature), i);
                const recoveredAddress = new XyoAddress({ publicKey }).address;
                const expectedAddress = Buffer.from(toUint8Array(address)).toString('hex');
                valid = valid || recoveredAddress === expectedAddress;
            }
            catch (ex) {
                null;
            }
        }
        return valid;
    }
}
// we do this to allow node to import without problem
// eslint-disable-next-line import/no-named-as-default-member
XyoAddress.ecContext = new EC.ec('secp256k1');
//# sourceMappingURL=Address.js.map
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % export * from './Address';
//# sourceMappingURL=index.js.map
export: not valid in this context: Creative Cloud Files
joshuanaylor@Joshuas-iMac ~ % {
  "data": [
    {
      "accessControl": false,
      "archive": "temp"
    }
  ],
  "meta": {
    "profile": {
      "duration": 0,
      "endTime": 1647896356183,
      "startTime": 1647896356183
    }
  }
}
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % curl -X 'GET' \
  'https://api.archivist.xyo.network/archive' \
  -H 'accept: application/json'
{"data":[{"accessControl":false,"archive":"temp"}],"meta":{"profile":{"duration":0,"endTime":1647896433613,"startTime":1647896433613}}}%                        joshuanaylor@Joshuas-iMac ~ % https://api.archivist.xyo.network/archive
zsh: no such file or directory: https://api.archivist.xyo.network/archive
joshuanaylor@Joshuas-iMac ~ % {
  "data": [
    {
      "accessControl": false,
      "archive": "temp"
    }
  ],
  "meta": {
    "profile": {
      "duration": 0,
      "endTime": 1647896356183,
      "startTime": 1647896356183
    }
  }
}
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % >....                                             
          "Schema"
        ],
        "summary": "Get recent payloads filtered by schema",
        "description": "",
        "parameters": [
          {
            "name": "archive",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "schema",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {}
      }
    }
  }
}
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % >....                                             
          "Schema"
        ],
        "summary": "Get recent payloads filtered by schema",
        "description": "",
        "parameters": [
          {
            "name": "archive",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "schema",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {}
      }
    }
  }
}
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % a275264e-a082-4a9b-858c-9bc3b3e8870d
zsh: command not found: a275264e-a082-4a9b-858c-9bc3b3e8870d
joshuanaylor@Joshuas-iMac ~ % >....                                             
    "pins": [
      {
        "package": "Alamofire",
        "repositoryURL": "https://github.com/Alamofire/Alamofire.git",
        "state": {
          "branch": null,
          "revision": "f82c23a8a7ef8dc1a49a8bfc6a96883e79121864",
          "version": "5.5.0"
        }
      },
      {
        "package": "secp256k1",
        "repositoryURL": "https://github.com/GigaBitcoin/secp256k1.swift.git",
        "state": {
          "branch": null,
          "revision": "c61f15293e1c4617299b8b91efdd06f583de1148",
          "version": "0.4.0"
        }
      }
    ]
  },
  "version": 1
}
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % >....                                             
    "pins": [
      {
        "package": "Alamofire",
        "repositoryURL": "https://github.com/Alamofire/Alamofire.git",
        "state": {
          "branch": null,
          "revision": "f82c23a8a7ef8dc1a49a8bfc6a96883e79121864",
          "version": "5.5.0"
        }
      },
      {
        "package": "secp256k1",
        "repositoryURL": "https://github.com/GigaBitcoin/secp256k1.swift.git",
        "state": {
          "branch": null,
          "revision": "c61f15293e1c4617299b8b91efdd06f583de1148",
          "version": "0.4.0"
        }
      }
    ]
  },
  "version": 1
}
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % >....                                             
    "pins": [
      {
        "package": "Alamofire",
        "repositoryURL": "https://github.com/Alamofire/Alamofire.git",
        "state": {
          "branch": null,
          "revision": "f82c23a8a7ef8dc1a49a8bfc6a96883e79121864",
          "version": "5.5.0"
        }
      },
      {
        "package": "secp256k1",
        "repositoryURL": "https://github.com/GigaBitcoin/secp256k1.swift.git",
        "state": {
          "branch": null,
          "revision": "c61f15293e1c4617299b8b91efdd06f583de1148",
          "version": "0.4.0"
        }
      }
    ]
  },
  "version": 1
}
zsh: parse error near `}'
joshuanaylor@Joshuas-iMac ~ % joshuanaylor@Joshuas-iMac ~ % npm i --save @xyo-network/sdk-xyo-client-js
yarn add @xyo-network/sdk-xyo-client-js
npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.
zsh: command not found: joshuanaylor@Joshuas-iMac
zsh: command not found: yarn

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/joshuanaylor/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.13 /usr/local/lib/node_modules/npm

joshuanaylor@Joshuas-iMac ~ %

**Comment by arietrouw** [comment]
Please post following fields:

1. Observed Behavior
2. Expected Behavior
3. Environment being used in
4. Steps to reproduce

Also, I think this is in the wrong repo. The is the SWIFT SDK. Please move this to: https://github.com/XYOracleNetwork/sdk-xyo-client-js/issues

**Comment by Rancid1616** [comment]
How do I do that? I don't know where to find that
